# Generated by Django 4.2.3 on 2023-07-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('manager', 'manager'), ('accountant', 'accountant'), ('security', 'security')], max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('reg_number', models.CharField(max_length=50)),
                ('reg_date', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('contact_person', models.CharField(max_length=50)),
                ('total_employees', models.IntegerField()),
                ('cell', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('departments', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.department', verbose_name='departments')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
